name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check Out Repo 
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push mainline/alpine
        uses: docker/build-push-action@v2
        with:
          context: ./mainline/alpine
          push: true
          tags: docker.io/denji/nginx-libressl:mainline-alpine
          cache-from: type=registry,ref=docker.io/denji/nginx-libressl:mainline-alpine
          cache-to: type=inline
      -
        name: Build and push stable/alpine
        uses: docker/build-push-action@v2
        with:
          context: ./stable/alpine
          push: true
          tags: docker.io/denji/nginx-libressl:stable-alpine
          cache-from: type=registry,ref=docker.io/denji/nginx-libressl:stable-alpine
          cache-to: type=inline
